### PR TITLE
tintin: add new package

### PR DESCRIPTION
**Pull request by wzyou**
Signed-off-by: wzyou <wzyou.goo@gmail.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by wzyou** [comment]
可以

**Comment by wzyou** [comment]
测试通过了；又删除了一些不必要的configure配置参数

**Comment by Beginner-Go** [comment]
就是您commit.有点混乱 建议整理一下

**Comment by wzyou** [comment]
整理完成了，第次使用 pull request , 花了些功夫

**Comment by Beginner-Go** [comment]
thank you pr

**Comment by Beginner-Go** [comment]
建议提交到官方

**Pull request merged**
