### PR TITLE
add fail2ban

### PR DESCRIPTION
**Pull request by lxhao61**
Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by Beginner-Go** [comment]
what?

**Comment by lxhao61** [comment]
> what?

http://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by Beginner-Go** [comment]
applicable to China?

**Comment by lxhao61** [comment]
> applicable to china?

当然呀。

**Comment by Beginner-Go** [comment]
can you test compile？

**Comment by lxhao61** [comment]
> can you test compile？

我已经编译过多次无问题。见我云编译https://github.com/lxhao61/Actions-Lean-OpenWrt

**Pull request closed without merging**
